[package]
name = "haltrepro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
mshv-bindings = {git = "https://github.com/rust-vmm/mshv"}
mshv-ioctls  = {git = "https://github.com/rust-vmm/mshv"}
anyhow = "1.0"
